import numpy as np


def calculate_fitness(individual, distance_matrix):
    total_distance = 0
    for i in range(len(individual) - 1):
        current_city = individual[i]  # Use as integer
        next_city = individual[i + 1]  # Use as integer
        total_distance += distance_matrix[current_city][next_city]
    return total_distance



def select_in_tournament(population, scores, number_tournaments=4, tournament_size=3):
    """
    Tournament selection for genetic algorithm.
    Selects individuals from the population based on their fitness scores.
    """
    selected = []
    
    for _ in range(number_tournaments):
        # Randomly select `tournament_size` individuals from the population
        idx = np.random.choice(len(population), tournament_size, replace=False)
        
        # Find the individual with the best fitness score (highest fitness score)
        best_idx = idx[np.argmax(scores[idx])]
        
        # Add the best individual to the selected list
        selected.append(population[best_idx])
    
    return selected

def order_crossover(parent1, parent2):
    """
    Order crossover (OX) for permutations.

    Parameters:
        - parent1 (list): The first parent route.
        - parent2 (list): The second parent route.

    Returns:
        - list: The offspring route generated by the crossover.
    """
    size = len(parent1)
    start, end = sorted(np.random.choice(range(size), 2, replace=False))
    offspring = [None] * size
    offspring[start:end + 1] = parent1[start:end + 1]
    fill_values = [x for x in parent2 if x not in offspring[start:end + 1]]
    idx = 0
    for i in range(size):
        if offspring[i] is None:
            offspring[i] = fill_values[idx]
            idx += 1
    return offspring


def mutate(route,
           mutation_rate = 0.1):
    """
    Mutation operator: swap two nodes in the route.

    Parameters:
        - route (list): The route to mutate.
        - mutation_rate (float): The chance to mutate an individual.
    Returns:
        - list: The mutated route.
    """
    if np.random.rand() < mutation_rate:
        i, j = np.random.choice(len(route), 2, replace=False)
        route[i], route[j] = route[j], route[i]
    return route

def generate_unique_population(population_size, num_nodes):
    """
    Generate a unique population of individuals for a genetic algorithm.

    Each individual in the population represents a route in a graph, where the first node is fixed (0) and the 
    remaining nodes are a permutation of the other nodes in the graph. This function ensures that all individuals
    in the population are unique.

    Parameters:
        - population_size (int): The desired size of the population.
        - num_nodes (int): The number of nodes in the graph, including the starting node.

    Returns:
        - list of lists: A list of unique individuals, where each individual is represented as a list of node indices.
    """
    population = set()
    while len(population) < population_size:
        individual = [0] + list(np.random.permutation(np.arange(1, num_nodes)))
        population.add(tuple(individual))
    return [list(ind) for ind in population]
